### PR TITLE
Fixed rewind and fast forward behavior

### PR DESCRIPTION
**Pull request by KBerstene**
The fast forward IF statement here should be an AND, not an OR.  I also added a similar statement for rewind, so that if it's playing the first track, it will show rewind instead of previous just like how the fast forward should show if it's the last track instead of next.

### CODE REVIEW

**Comment by glennguy** [comment]
I understand what the intent is here, but what happens when repeat is enabled i.e queue up an album and enable repeat? I'm thinking that you won't be able to skip past the last song to the start of the album and go from the first to the last track as you can currently.

In reworking the notifications I tried to follow the layout of GPM in order to provide familiarity and predictable behaviour for users, while also keeping the controls in line with the in app controls. That said there's still room for improvement.

I've just checked and GPM will allow you to skip next or previous from the last or first track of the playlist respectfully, regardless of the repeat setting. The repeat setting only seems to determine the behaviour when a track completes. This might be a solution for us that prevents having 'useless' buttons on the notification while keeping the controls more consistent.

I'm interested to hear your thoughts and opinion of how this should be set. From what I can see, the fast forward/rewind controls seem to be geared mainly towards podcasts: ` public synchronized boolean shouldFastForward() {
		return size() == 1 || (currentPlaying != null && !currentPlaying.isSong());`

**Comment by KBerstene** [comment]
I just tested having repeat on. If you have repeat all on and fast forward past the end of the last track, you will skip to the next track.

I agree that the basic layout of the notification is good, and I like it quite a bit over the old notification (which I've had issues with in the past).  The changes that I submitted are actually bringing it in line with DSub's current behavior in the "Now Playing" fragment.  The root problem is actually with this behavior--specifically, that having rewind enabled won't skip to the previous track no matter the position of the currently playing song in the list.  Fast forward works perfectly fine to skip to the next track, even with the repeat all on (though with repeat single, it will loop in that single track).

Edit because I'm bad at getting to the point: Really, I think what I'm trying to say here is that this notification should have the same behavior as the other sections of DSub, which are already all over the place.  The Now Playing fragment should be the "master" for determining behavior.  The notification, home screen widget, and Auto widget should all follow its behavior so it's predictable across the board.

**Comment by KBerstene** [comment]
Actually, it looks like I am mistaken with some of the behavior I was seeing.  For some reason I had mixed some things up with different code.  Reviewing everything right now, I'm seeing that the previous/next buttons and ff/rewind buttons are always matched together in the Now Playing fragment.  I'm not sure why I had a different impression.  I still do want to keep the ff/rewind buttons paired together, so I will push another commit to this branch to correct my mistake, removing the AND statement and simply setting ff/previous with shouldFastForward().

This should properly match the NowPlaying fragment by simply removing the "fast forward if this is the final track" behavior.  It also removes an odd if/if and replaces it with an equivalent if/else.

**Comment by glennguy** [comment]
Fantastic, thanks for that! I totally got it wrong with having ff enabled on the last track.

Next thing I think is to allow next/prev track when repeat is turned off, but that's not for this PR.

**Comment by glennguy** [comment]
Also I've noticed that once a playlist finishes, pressing play won't start it again. It's not obvious what's happening from the notification but in Android Auto you can see that the track gets updated to the first track, however the buttons are as if it's still on the last track.
I haven't looked into it yet but I'm sure the issue is somewhere in RemoteControlClientLP.

**Pull request merged**
